databases:
  - name: bookingsdb
    plan: free
    databaseName: bookings
    user: dakota

services:
  - type: web
    plan: free
    name: bookings
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'cd homework2; python -m gunicorn movie_theater_booking.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookingsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4